const types = Object.freeze({
  ADD_TASK: "ADD_TASK",
  SET_TASKS: "SET_TASKS",
  EDIT_TASK: "EDIT_TASK",
  SET_STATUS: "SET_STATUS",
  SET_SORT_DATE: "SET_SORT_DATE",
  TOGGLE_LOADING: "TOGGLE_LOADING",
  DELETE_ONE_TASK: "DELETE_ONE_TASK",
  RESET_SEARCH_FORM: "RESET_SEARCH_FORM",
  TOGGLE_CHECK_TASK: "TOGGLE_CHECK_TASK",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  TOGGLE_ACTIVE_TASK: "TOGGLE_ACTIVE_TASK",
  CHANGE_SEARCH_VALUE: "CHANGE_SEARCH_VALUE",
  SET_SUCCESS_MESSAGE: "SET_SUCCESS_MESSAGE",
  DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
  TOGGLE_CHECK_ALL_TASKS: "TOGGLE_CHECK_ALL_TASKS",
  TOGGLE_OPEN_CONFIRM_MODAL: "TOGGLE_OPEN_CONFIRM_MODAL", 
  TOGGLE_OPEN_ADD_TASK_MODAL: "TOGGLE_OPEN_ADD_TASK_MODAL",
  SET_OR_REMOVE_EDITABLE_TASK: "SET_OR_REMOVE_EDITABLE_TASK"
})

export default types;